separator=""
separator_color="white"
key_color="blue"
#prefer_small_ascii=false

[palette]
type="Dark"
visible=false
glyph="â¬¤ "

[box]
title=" abeğŸŒŠ "
border="rounded"
color="red"
visible=true

[bar]
glyph="â–£"
hide_delimiters=true
visible=true

[randomize]
key_color=false
separator_color=false

[custom_ascii]
color="blue"
path="~/.config/macchina/themes/ascii-art.txt"

[keys]
host="ï€•"
machine="ó°·µ"
kernel="îœ’"
distro="ó±©"
cpu="ó°›"
cpu_load="î¿"
memory="î¿…"
disk_space="ó°‹Š"
terminal="î•"
shell="îš‘"

